"""
US State building code adoption database.
Data reflects commonly adopted codes as of 2024.
"""

STATE_CODES = {
    "AK": {
        "name": "Alaska",
        "building": {"name": "Alaska Building Code 2021", "based_on": "IBC 2018", "year": 2021},
        "residential": {"name": "Alaska Residential Code 2021", "based_on": "IRC 2018", "year": 2021},
        "energy": {"name": "IECC 2021", "based_on": "IECC 2021", "year": 2021},
        "mechanical": {"name": "Alaska Mechanical Code 2021", "based_on": "IMC 2018", "year": 2021},
        "plumbing": {"name": "Alaska Plumbing Code 2021", "based_on": "IPC 2018", "year": 2021},
        "fire": {"name": "Alaska Fire Code 2021", "based_on": "IFC 2018", "year": 2021},
        "upcodes_slug": "alaska",
    },
    "AL": {
        "name": "Alabama",
        "building": {"name": "Alabama Building Code 2019", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Alabama Residential Code 2019", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "IECC 2009", "based_on": "IECC 2009", "year": 2012},
        "mechanical": {"name": "Alabama Mechanical Code 2019", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Alabama Plumbing Code 2019", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "Alabama Fire Prevention Code", "based_on": "NFPA 1", "year": 2019},
        "upcodes_slug": "alabama",
    },
    "AR": {
        "name": "Arkansas",
        "building": {"name": "Arkansas Fire Prevention Code", "based_on": "IBC 2012", "year": 2014},
        "residential": {"name": "Arkansas Residential Building Code", "based_on": "IRC 2012", "year": 2014},
        "energy": {"name": "Arkansas Energy Code", "based_on": "IECC 2009", "year": 2012},
        "mechanical": {"name": "Arkansas Mechanical Code", "based_on": "IMC 2012", "year": 2014},
        "plumbing": {"name": "Arkansas Plumbing Code", "based_on": "IPC 2012", "year": 2014},
        "fire": {"name": "Arkansas Fire Prevention Code", "based_on": "IFC 2012", "year": 2014},
        "upcodes_slug": "arkansas",
    },
    "AZ": {
        "name": "Arizona",
        "building": {"name": "Arizona State Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Arizona Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Arizona Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Arizona Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Arizona Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "Arizona Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "arizona",
        "notes": "Adoption varies by municipality; Phoenix and Tucson may have local amendments.",
    },
    "CA": {
        "name": "California",
        "building": {"name": "California Building Code (CBC) 2022", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "California Residential Code (CRC) 2022", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "California Energy Code (Title 24) 2022", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "California Mechanical Code 2022", "based_on": "CMC 2022", "year": 2023},
        "plumbing": {"name": "California Plumbing Code 2022", "based_on": "CPC 2022", "year": 2023},
        "fire": {"name": "California Fire Code 2022", "based_on": "IFC 2021", "year": 2023},
        "upcodes_slug": "california",
        "notes": "California adopts its own statewide codes (CBC, CRC, Title 24) with extensive amendments. Local jurisdictions may adopt additional amendments.",
    },
    "CO": {
        "name": "Colorado",
        "building": {"name": "Colorado Building Code", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "Colorado Residential Code", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "Colorado Energy Code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Colorado Mechanical Code", "based_on": "IMC 2021", "year": 2023},
        "plumbing": {"name": "Colorado Plumbing Code", "based_on": "IPC 2021", "year": 2023},
        "fire": {"name": "Colorado Fire Code", "based_on": "IFC 2021", "year": 2023},
        "upcodes_slug": "colorado",
        "notes": "State adopts codes as guidelines; local adoption required. Denver and other cities may have their own amendments.",
    },
    "CT": {
        "name": "Connecticut",
        "building": {"name": "Connecticut State Building Code 2022", "based_on": "IBC 2021", "year": 2022},
        "residential": {"name": "Connecticut Residential Code 2022", "based_on": "IRC 2021", "year": 2022},
        "energy": {"name": "Connecticut Energy Code 2022", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Connecticut Mechanical Code 2022", "based_on": "IMC 2021", "year": 2022},
        "plumbing": {"name": "Connecticut Plumbing Code 2022", "based_on": "IPC 2021", "year": 2022},
        "fire": {"name": "Connecticut Fire Safety Code 2022", "based_on": "IFC 2021", "year": 2022},
        "upcodes_slug": "connecticut",
    },
    "DC": {
        "name": "District of Columbia",
        "building": {"name": "DC Building Code 2020", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "DC Residential Code 2020", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "DC Energy Conservation Code 2020", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "DC Mechanical Code 2020", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "DC Plumbing Code 2020", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "DC Fire Prevention Code 2020", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "district-of-columbia",
    },
    "DE": {
        "name": "Delaware",
        "building": {"name": "Delaware Building Code 2019", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Delaware Residential Code 2019", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Delaware Energy Code 2019", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "Delaware Mechanical Code 2019", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Delaware Plumbing Code 2019", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "Delaware Fire Prevention Code 2019", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "delaware",
    },
    "FL": {
        "name": "Florida",
        "building": {"name": "Florida Building Code 7th Edition (2020)", "based_on": "IBC 2018", "year": 2021},
        "residential": {"name": "Florida Building Code - Residential 7th Edition (2020)", "based_on": "IRC 2018", "year": 2021},
        "energy": {"name": "Florida Building Code - Energy Conservation 7th Edition", "based_on": "IECC 2018", "year": 2021},
        "mechanical": {"name": "Florida Building Code - Mechanical 7th Edition", "based_on": "IMC 2018", "year": 2021},
        "plumbing": {"name": "Florida Building Code - Plumbing 7th Edition", "based_on": "IPC 2018", "year": 2021},
        "fire": {"name": "Florida Fire Prevention Code 7th Edition", "based_on": "NFPA 1", "year": 2021},
        "upcodes_slug": "florida",
        "notes": "Florida adopts statewide codes every three years. Miami-Dade and Broward counties have additional High-Velocity Hurricane Zone (HVHZ) requirements.",
    },
    "GA": {
        "name": "Georgia",
        "building": {"name": "Georgia State Minimum Standard Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Georgia State Minimum Standard Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Georgia Energy Code", "based_on": "IECC 2015", "year": 2020},
        "mechanical": {"name": "Georgia Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Georgia Plumbing Code", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "Georgia Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "georgia",
    },
    "HI": {
        "name": "Hawaii",
        "building": {"name": "Hawaii State Building Code 2020", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Hawaii State Residential Code 2020", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Hawaii State Energy Conservation Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Hawaii State Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Hawaii State Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "Hawaii State Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "hawaii",
    },
    "IA": {
        "name": "Iowa",
        "building": {"name": "Iowa State Building Code", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Iowa Residential Code", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Iowa Energy Code", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Iowa Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Iowa Plumbing Code", "based_on": "UPC 2018", "year": 2019},
        "fire": {"name": "Iowa Fire Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "iowa",
    },
    "ID": {
        "name": "Idaho",
        "building": {"name": "Idaho Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Idaho Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Idaho Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Idaho Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Idaho Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "Idaho Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "idaho",
    },
    "IL": {
        "name": "Illinois",
        "building": {"name": "Illinois State Building Code", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "Illinois Residential Code", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "Illinois Energy Conservation Code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Illinois Mechanical Code", "based_on": "IMC 2021", "year": 2023},
        "plumbing": {"name": "Illinois Plumbing Code", "based_on": "IPC 2021", "year": 2023},
        "fire": {"name": "Illinois Fire Prevention Code", "based_on": "IFC 2021", "year": 2023},
        "upcodes_slug": "illinois",
        "notes": "Chicago has its own building code which differs significantly from the state code.",
    },
    "IN": {
        "name": "Indiana",
        "building": {"name": "Indiana Building Code 2020", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Indiana Residential Code 2020", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Indiana Energy Conservation Code", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Indiana Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Indiana Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "Indiana Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "indiana",
    },
    "KS": {
        "name": "Kansas",
        "building": {"name": "Kansas Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Kansas Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Kansas Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Kansas Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Kansas Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "Kansas Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "kansas",
        "notes": "No mandatory statewide code; adoption varies by local jurisdiction.",
    },
    "KY": {
        "name": "Kentucky",
        "building": {"name": "Kentucky Building Code 2018", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Kentucky Residential Code 2018", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Kentucky Energy Code", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "Kentucky Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Kentucky Plumbing Code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "Kentucky Fire Prevention Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "kentucky",
    },
    "LA": {
        "name": "Louisiana",
        "building": {"name": "Louisiana State Uniform Construction Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Louisiana Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Louisiana Energy Code", "based_on": "IECC 2015", "year": 2020},
        "mechanical": {"name": "Louisiana Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Louisiana Plumbing Code", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "Louisiana Fire Prevention Code", "based_on": "NFPA 1", "year": 2020},
        "upcodes_slug": "louisiana",
    },
    "MA": {
        "name": "Massachusetts",
        "building": {"name": "Massachusetts State Building Code (780 CMR) 9th Edition", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "Massachusetts One- and Two-Family Dwelling Code (780 CMR)", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "Massachusetts Stretch Energy Code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Massachusetts Mechanical Code", "based_on": "IMC 2021", "year": 2023},
        "plumbing": {"name": "Massachusetts Plumbing Code", "based_on": "IPC 2021", "year": 2023},
        "fire": {"name": "Massachusetts Fire Prevention Regulations (527 CMR)", "based_on": "NFPA 1", "year": 2023},
        "upcodes_slug": "massachusetts",
        "notes": "Massachusetts has a mandatory Stretch Code for energy efficiency that exceeds IECC minimums, adopted by many municipalities.",
    },
    "MD": {
        "name": "Maryland",
        "building": {"name": "Maryland Building Performance Standards", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "Maryland Building Performance Standards - Residential", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "Maryland Energy Code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Maryland Mechanical Code", "based_on": "IMC 2021", "year": 2023},
        "plumbing": {"name": "Maryland Plumbing Code", "based_on": "IPC 2021", "year": 2023},
        "fire": {"name": "Maryland Fire Prevention Code", "based_on": "NFPA 1", "year": 2023},
        "upcodes_slug": "maryland",
    },
    "ME": {
        "name": "Maine",
        "building": {"name": "Maine Building Code", "based_on": "IBC 2015", "year": 2018},
        "residential": {"name": "Maine Residential Code", "based_on": "IRC 2015", "year": 2018},
        "energy": {"name": "Maine Energy Code", "based_on": "IECC 2015", "year": 2018},
        "mechanical": {"name": "Maine Mechanical Code", "based_on": "IMC 2015", "year": 2018},
        "plumbing": {"name": "Maine Plumbing Code", "based_on": "IPC 2015", "year": 2018},
        "fire": {"name": "Maine Fire Prevention Code", "based_on": "NFPA 1", "year": 2018},
        "upcodes_slug": "maine",
    },
    "MI": {
        "name": "Michigan",
        "building": {"name": "Michigan Building Code 2015", "based_on": "IBC 2015", "year": 2016},
        "residential": {"name": "Michigan Residential Code 2015", "based_on": "IRC 2015", "year": 2016},
        "energy": {"name": "Michigan Energy Code 2015", "based_on": "IECC 2015", "year": 2016},
        "mechanical": {"name": "Michigan Mechanical Code 2015", "based_on": "IMC 2015", "year": 2016},
        "plumbing": {"name": "Michigan Plumbing Code 2015", "based_on": "IPC 2015", "year": 2016},
        "fire": {"name": "Michigan Fire Prevention Code", "based_on": "NFPA 1", "year": 2016},
        "upcodes_slug": "michigan",
    },
    "MN": {
        "name": "Minnesota",
        "building": {"name": "Minnesota State Building Code", "based_on": "IBC 2020", "year": 2022},
        "residential": {"name": "Minnesota Residential Code", "based_on": "IRC 2020", "year": 2022},
        "energy": {"name": "Minnesota Energy Code", "based_on": "IECC 2020", "year": 2022},
        "mechanical": {"name": "Minnesota Mechanical Code", "based_on": "IMC 2020", "year": 2022},
        "plumbing": {"name": "Minnesota Plumbing Code", "based_on": "IPC 2020", "year": 2022},
        "fire": {"name": "Minnesota State Fire Code", "based_on": "IFC 2020", "year": 2022},
        "upcodes_slug": "minnesota",
    },
    "MO": {
        "name": "Missouri",
        "building": {"name": "Missouri Building Code", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Missouri Residential Code", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Missouri Energy Code", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "Missouri Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Missouri Plumbing Code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "Missouri Fire Safety Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "missouri",
        "notes": "No mandatory statewide code for one- and two-family dwellings; municipalities adopt independently.",
    },
    "MS": {
        "name": "Mississippi",
        "building": {"name": "Mississippi State Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Mississippi Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Mississippi Energy Code", "based_on": "IECC 2015", "year": 2020},
        "mechanical": {"name": "Mississippi Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Mississippi Plumbing Code", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "Mississippi Fire Prevention Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "mississippi",
    },
    "MT": {
        "name": "Montana",
        "building": {"name": "Montana Building Codes", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "Montana Residential Code", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "Montana Energy Code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Montana Mechanical Code", "based_on": "IMC 2021", "year": 2023},
        "plumbing": {"name": "Montana Plumbing Code", "based_on": "UPC 2021", "year": 2023},
        "fire": {"name": "Montana Fire Code", "based_on": "IFC 2021", "year": 2023},
        "upcodes_slug": "montana",
    },
    "NC": {
        "name": "North Carolina",
        "building": {"name": "North Carolina Building Code 2018", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "North Carolina Residential Code 2018", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "North Carolina Energy Conservation Code 2021", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "North Carolina Mechanical Code 2018", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "North Carolina Plumbing Code 2018", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "North Carolina Fire Prevention Code 2018", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "north-carolina",
    },
    "ND": {
        "name": "North Dakota",
        "building": {"name": "North Dakota State Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "North Dakota Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "North Dakota Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "North Dakota Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "North Dakota Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "North Dakota Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "north-dakota",
    },
    "NE": {
        "name": "Nebraska",
        "building": {"name": "Nebraska Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Nebraska Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Nebraska Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Nebraska Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Nebraska Plumbing Code", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "Nebraska Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "nebraska",
    },
    "NH": {
        "name": "New Hampshire",
        "building": {"name": "New Hampshire Building Code 2022", "based_on": "IBC 2021", "year": 2022},
        "residential": {"name": "New Hampshire Residential Code 2022", "based_on": "IRC 2021", "year": 2022},
        "energy": {"name": "New Hampshire Energy Code 2022", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "New Hampshire Mechanical Code 2022", "based_on": "IMC 2021", "year": 2022},
        "plumbing": {"name": "New Hampshire Plumbing Code 2022", "based_on": "IPC 2021", "year": 2022},
        "fire": {"name": "New Hampshire Fire Code 2022", "based_on": "IFC 2021", "year": 2022},
        "upcodes_slug": "new-hampshire",
    },
    "NJ": {
        "name": "New Jersey",
        "building": {"name": "New Jersey Uniform Construction Code (UCC) 2018", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "New Jersey Residential Code 2018", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "New Jersey Energy Sub-code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "New Jersey Mechanical Sub-code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "New Jersey Plumbing Sub-code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "New Jersey Fire Protection Sub-code", "based_on": "NFPA 101", "year": 2019},
        "upcodes_slug": "new-jersey",
    },
    "NM": {
        "name": "New Mexico",
        "building": {"name": "New Mexico Commercial Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "New Mexico Residential Building Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "New Mexico Energy Conservation Code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "New Mexico Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "New Mexico Plumbing Code", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "New Mexico Fire Prevention Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "new-mexico",
    },
    "NV": {
        "name": "Nevada",
        "building": {"name": "Nevada Building Code 2018", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Nevada Residential Code 2018", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Nevada Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Nevada Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Nevada Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "Nevada State Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "nevada",
    },
    "NY": {
        "name": "New York",
        "building": {"name": "New York State Building Code 2020", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "New York State Residential Code 2020", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "New York State Energy Conservation Construction Code 2020", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "New York State Mechanical Code 2020", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "New York State Plumbing Code 2020", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "New York State Fire Prevention and Building Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "new-york",
        "notes": "New York City uses its own separate building code (NYC Building Code 2022) which differs significantly from the state code.",
    },
    "OH": {
        "name": "Ohio",
        "building": {"name": "Ohio Building Code 2023", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "Ohio Residential Code 2023", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "Ohio Energy Code 2023", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Ohio Mechanical Code 2023", "based_on": "IMC 2021", "year": 2023},
        "plumbing": {"name": "Ohio Plumbing Code 2023", "based_on": "IPC 2021", "year": 2023},
        "fire": {"name": "Ohio Fire Code 2023", "based_on": "IFC 2021", "year": 2023},
        "upcodes_slug": "ohio",
    },
    "OK": {
        "name": "Oklahoma",
        "building": {"name": "Oklahoma Uniform Building Code", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Oklahoma Residential Code", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Oklahoma Energy Code", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "Oklahoma Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Oklahoma Plumbing Code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "Oklahoma Fire Prevention Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "oklahoma",
        "notes": "Local adoption required; many jurisdictions adopt independently.",
    },
    "OR": {
        "name": "Oregon",
        "building": {"name": "Oregon Structural Specialty Code 2021", "based_on": "IBC 2021", "year": 2022},
        "residential": {"name": "Oregon Residential Specialty Code 2021", "based_on": "IRC 2021", "year": 2022},
        "energy": {"name": "Oregon Energy Efficiency Specialty Code 2021", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Oregon Mechanical Specialty Code 2021", "based_on": "IMC 2021", "year": 2022},
        "plumbing": {"name": "Oregon Plumbing Specialty Code", "based_on": "UPC 2021", "year": 2022},
        "fire": {"name": "Oregon Fire Code 2021", "based_on": "IFC 2021", "year": 2022},
        "upcodes_slug": "oregon",
    },
    "PA": {
        "name": "Pennsylvania",
        "building": {"name": "Pennsylvania Uniform Construction Code", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Pennsylvania Residential Code", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Pennsylvania Energy Conservation Code", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "Pennsylvania Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Pennsylvania Plumbing Code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "Pennsylvania Fire and Panic Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "pennsylvania",
    },
    "RI": {
        "name": "Rhode Island",
        "building": {"name": "Rhode Island State Building Code 2021", "based_on": "IBC 2021", "year": 2022},
        "residential": {"name": "Rhode Island One and Two Family Dwelling Code 2021", "based_on": "IRC 2021", "year": 2022},
        "energy": {"name": "Rhode Island Energy Code 2021", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Rhode Island Mechanical Code 2021", "based_on": "IMC 2021", "year": 2022},
        "plumbing": {"name": "Rhode Island Plumbing Code 2021", "based_on": "IPC 2021", "year": 2022},
        "fire": {"name": "Rhode Island Fire Safety Code 2021", "based_on": "IFC 2021", "year": 2022},
        "upcodes_slug": "rhode-island",
    },
    "SC": {
        "name": "South Carolina",
        "building": {"name": "South Carolina Building Code 2018", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "South Carolina Residential Code 2018", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "South Carolina Energy Code", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "South Carolina Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "South Carolina Plumbing Code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "South Carolina Fire Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "south-carolina",
    },
    "SD": {
        "name": "South Dakota",
        "building": {"name": "South Dakota Building Codes", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "South Dakota Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "South Dakota Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "South Dakota Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "South Dakota Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "South Dakota Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "south-dakota",
        "notes": "Statewide building codes apply only to state-owned buildings; local adoption required for other buildings.",
    },
    "TN": {
        "name": "Tennessee",
        "building": {"name": "Tennessee Building Codes 2018", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Tennessee Residential Building Codes 2018", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Tennessee Energy Code 2018", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "Tennessee Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Tennessee Plumbing Code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "Tennessee Fire Prevention Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "tennessee",
    },
    "TX": {
        "name": "Texas",
        "building": {"name": "Texas Building Code", "based_on": "IBC 2015", "year": 2016},
        "residential": {"name": "Texas Residential Code", "based_on": "IRC 2015", "year": 2016},
        "energy": {"name": "Texas Energy Code 2021", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Texas Mechanical Code", "based_on": "IMC 2015", "year": 2016},
        "plumbing": {"name": "Texas Plumbing Code", "based_on": "UPC 2018", "year": 2019},
        "fire": {"name": "Texas Fire Code", "based_on": "IFC 2015", "year": 2016},
        "upcodes_slug": "texas",
        "notes": "Texas building codes are largely adopted at the local level. Many jurisdictions (Houston, Dallas, Austin) have their own codes with local amendments. No mandatory statewide code for residential construction.",
    },
    "UT": {
        "name": "Utah",
        "building": {"name": "Utah Building Code 2018", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "Utah Residential Code 2018", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "Utah Energy Code 2018", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "Utah Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "Utah Plumbing Code", "based_on": "UPC 2018", "year": 2019},
        "fire": {"name": "Utah Fire Prevention and Safety Act", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "utah",
    },
    "VA": {
        "name": "Virginia",
        "building": {"name": "Virginia Uniform Statewide Building Code (USBC) 2021", "based_on": "IBC 2021", "year": 2022},
        "residential": {"name": "Virginia USBC Residential (Part II) 2021", "based_on": "IRC 2021", "year": 2022},
        "energy": {"name": "Virginia Energy Conservation Code 2021", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Virginia Mechanical Code 2021", "based_on": "IMC 2021", "year": 2022},
        "plumbing": {"name": "Virginia Plumbing Code 2021", "based_on": "IPC 2021", "year": 2022},
        "fire": {"name": "Virginia Statewide Fire Prevention Code 2021", "based_on": "IFC 2021", "year": 2022},
        "upcodes_slug": "virginia",
    },
    "VT": {
        "name": "Vermont",
        "building": {"name": "Vermont Fire and Building Safety Code 2020", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Vermont Residential Building Energy Standards", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Vermont Commercial Building Energy Standards", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Vermont Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Vermont Plumbing Code", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "Vermont Fire and Building Safety Code", "based_on": "NFPA 101", "year": 2020},
        "upcodes_slug": "vermont",
    },
    "WA": {
        "name": "Washington",
        "building": {"name": "Washington State Building Code 2021", "based_on": "IBC 2021", "year": 2023},
        "residential": {"name": "Washington State Residential Code 2021", "based_on": "IRC 2021", "year": 2023},
        "energy": {"name": "Washington State Energy Code 2021", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Washington State Mechanical Code 2021", "based_on": "IMC 2021", "year": 2023},
        "plumbing": {"name": "Washington State Plumbing Code 2021", "based_on": "UPC 2021", "year": 2023},
        "fire": {"name": "Washington State Fire Code 2021", "based_on": "IFC 2021", "year": 2023},
        "upcodes_slug": "washington",
    },
    "WI": {
        "name": "Wisconsin",
        "building": {"name": "Wisconsin Commercial Building Code", "based_on": "IBC 2015", "year": 2017},
        "residential": {"name": "Wisconsin Uniform Dwelling Code (UDC)", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Wisconsin Energy Conservation Code", "based_on": "IECC 2021", "year": 2023},
        "mechanical": {"name": "Wisconsin Mechanical Code", "based_on": "IMC 2015", "year": 2017},
        "plumbing": {"name": "Wisconsin Plumbing Code", "based_on": "IPC 2015", "year": 2017},
        "fire": {"name": "Wisconsin Fire Prevention Code", "based_on": "NFPA 1", "year": 2020},
        "upcodes_slug": "wisconsin",
    },
    "WV": {
        "name": "West Virginia",
        "building": {"name": "West Virginia State Building Code 2019", "based_on": "IBC 2018", "year": 2019},
        "residential": {"name": "West Virginia Residential Code 2019", "based_on": "IRC 2018", "year": 2019},
        "energy": {"name": "West Virginia Energy Conservation Code", "based_on": "IECC 2018", "year": 2019},
        "mechanical": {"name": "West Virginia Mechanical Code", "based_on": "IMC 2018", "year": 2019},
        "plumbing": {"name": "West Virginia Plumbing Code", "based_on": "IPC 2018", "year": 2019},
        "fire": {"name": "West Virginia Fire Code", "based_on": "IFC 2018", "year": 2019},
        "upcodes_slug": "west-virginia",
    },
    "WY": {
        "name": "Wyoming",
        "building": {"name": "Wyoming Building Codes", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Wyoming Residential Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Wyoming Energy Code", "based_on": "IECC 2018", "year": 2020},
        "mechanical": {"name": "Wyoming Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Wyoming Plumbing Code", "based_on": "UPC 2018", "year": 2020},
        "fire": {"name": "Wyoming Fire Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "wyoming",
        "notes": "No mandatory statewide building code; local adoption required.",
    },
}

# City-specific overrides for major cities with their own codes
CITY_OVERRIDES = {
    "new york city": {
        "state": "NY",
        "building": {"name": "NYC Building Code 2022", "based_on": "IBC 2021", "year": 2022},
        "residential": {"name": "NYC Building Code 2022 (Residential)", "based_on": "IBC 2021", "year": 2022},
        "energy": {"name": "NYC Energy Conservation Code 2022", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "NYC Mechanical Code 2022", "based_on": "IMC 2021", "year": 2022},
        "plumbing": {"name": "NYC Plumbing Code 2022", "based_on": "IPC 2021", "year": 2022},
        "fire": {"name": "NYC Fire Code 2022", "based_on": "IFC 2021", "year": 2022},
        "upcodes_slug": "new-york-city",
        "notes": "New York City maintains its own comprehensive building code, separate from New York State code.",
    },
    "chicago": {
        "state": "IL",
        "building": {"name": "Chicago Building Code", "based_on": "IBC 2018", "year": 2020},
        "residential": {"name": "Chicago Residential Building Code", "based_on": "IRC 2018", "year": 2020},
        "energy": {"name": "Chicago Energy Conservation Code", "based_on": "IECC 2021", "year": 2022},
        "mechanical": {"name": "Chicago Mechanical Code", "based_on": "IMC 2018", "year": 2020},
        "plumbing": {"name": "Chicago Plumbing Code", "based_on": "IPC 2018", "year": 2020},
        "fire": {"name": "Chicago Fire Prevention Code", "based_on": "IFC 2018", "year": 2020},
        "upcodes_slug": "chicago",
        "notes": "Chicago maintains its own building code with significant local amendments.",
    },
}

UPCODES_BASE_URL = "https://up.codes/viewer"

CODE_CATEGORIES = [
    {"key": "building", "label": "Building Code", "icon": "Building2", "color": "blue"},
    {"key": "residential", "label": "Residential Code", "icon": "Home", "color": "green"},
    {"key": "energy", "label": "Energy Code", "icon": "Zap", "color": "yellow"},
    {"key": "mechanical", "label": "Mechanical Code", "icon": "Wind", "color": "purple"},
    {"key": "plumbing", "label": "Plumbing Code", "icon": "Droplets", "color": "cyan"},
    {"key": "fire", "label": "Fire Code", "icon": "Flame", "color": "red"},
]


def get_codes_for_jurisdiction(state_abbr: str, city: str = "") -> dict:
    """Return building codes for a given state/city jurisdiction."""
    city_lower = city.lower().strip()

    # Check city overrides first
    for city_key, city_data in CITY_OVERRIDES.items():
        if city_key in city_lower and city_data["state"] == state_abbr.upper():
            return {**city_data, "jurisdiction_type": "city", "city": city}

    state_upper = state_abbr.upper()
    if state_upper in STATE_CODES:
        data = STATE_CODES[state_upper].copy()
        data["jurisdiction_type"] = "state"
        return data

    return None


def build_upcodes_url(slug: str, section: str = "") -> str:
    """Build a UpCodes URL for a given jurisdiction slug and optional section."""
    base = f"{UPCODES_BASE_URL}/{slug}"
    if section:
        return f"{base}/{section}"
    return base
